            <div class="icon-box">
              <a href="/gestalt-keylogger/files/GestaltKeyLoggerSetup.exe" class="btn-download-now">Download Now</a>
              <br /><br />
              <span><b>File size</b>: 9 Mb</span><br /><br />
              <span><b>Latest version</b>: 1.0.1</span><br /><br />
              <span><b>Released on</b>: April 1, 2021</span><br /><br />
            </div>
